### ISSUE TITLE
Get authorizer by `scope` rather than resource server id

### ISSUE THREAD

**Issue by jimPruyne** [fair-research/native-login#24]
Given that `login()` can take a tuple of `requested_scopes`, it makes sense(?) to be able to do something like `get_authorizers()` but have that return something I can index by scope rather than by resource server. Without that, there seems to be a disconnect between how I specify what I want (scope) and how I find what I get back (resource server) unless I already know those relationships (which maybe I usually would, but we're still asking users to think about similar stuff in two different ways and it gets confusing).

**Comment by rpwagner** [comment]
Should we take it further and just go for `get_client('<scope>')`? We can map the scopes to known client types (Search, Transfer, etc.) and return the base client to do general REST calls. I don't know if `AccessTokenAuthorizer`s have much use otherwise.

**Comment by jimPruyne** [comment]
> Should we take it further and just go for `get_client('<scope>')`? We can map the scopes to known client types (Search, Transfer, etc.) and return the base client to do general REST calls. I don't know if `AccessTokenAuthorizer`s have much use otherwise.

I think that's taking it a step too far. In my cases, the value here is in generating new types of clients with the login and even Authorizer creation handled. In this case, I really do want the Authorizer and then I'm set to implement the client as an extension of the Globus SDK base client class.

**Comment by rpwagner** [comment]
Makes sense. And if the Authorizer is being used, then it's likely the developer will be writing a custom subclass rather than making raw HTTPS calls.

**Comment by NickolausDS** [comment]
Getting authorizers by scope seems reasonable enough. For symmetry, I propose two additional methods:

* `load_tokens_by_scope` -- dict of token dicts keyed by scope
* `get_authorizers_by_scope` -- dict of authorizers keyed by scope

Apart from loading tokens or authorizers, something like `get_client()` would require some investigation. It would be easy to track known clients (search, transfer, auth, identifiers) but we would have to start making assumptions about registering unknown clients. For instance, will all clients subclass the Globus SDK Base Client? I don't think `BaseClient` is advertised as a top level import, so this may not be recommended for third parties. Alternatively, do we want to assume all clients will implement the keyword `authorizers` in their `__init__` methods (The duck typing approach)? It would be a nice feature, but also means opening that can of worms. I'll open an issue for it.

**Comment by jimPruyne** [comment]
I think the proposed `get_authorizers_by_scope` is essentially what I'm requesting.

It is not clear to me what the intent of `load_tokens_by_scope` would do.

I think @rpwagner and I agreed in follow on here that trying to raise anything to the level of returning clients of any sort is going a step too far. For the known client types (ie those defined in the main SDK), this is really not needed, and for other client types there's little value since the client would have to be simply a `BaseClient` which pretty much any new implementation would be looking to extend.

**Comment by rpwagner** [comment]
That's correct, we shouldn't do anything with clients unless we have clearer use cases for arbitrary clients.

**Comment by rpwagner** [comment]
And loading by scope doesn't seem necessary at the moment. The tokens dictionary isn't that unwieldy. Maybe some examples of how to load tokens and list the set of current scopes instead.

**Comment by NickolausDS** [comment]
@jimPruyne 

> It is not clear to me what the intent of load_tokens_by_scope would do.

Currently there is a function `load_tokens` which loads tokens by resource server. For your specific use case, it seems like you can use authorizers directly. For other custom clients that can't work with authorizers but still want to fetch a corresponding access token for a given scope, it poses a bit of a problem. It's still possible to extract a token from an authorizer, but that seems more like a workaround. Why not allow them to fetch the token by scope directly? 

That said, I'm not really sure of the use-cases for requesting access_tokens by scope. That seems implied by the resource server and the value passed as `requested_scopes=` for `load_tokens()` and `login()`, at least for simple use cases. #22 is worth mentioning in that context.

**Comment by NickolausDS** [comment]
Added #25 for any further discussion on `get_clients`, whether we want to pursue it at some point or decide not to.

**Comment by jimPruyne** [comment]
I think the confusion here might be the use of "get" and "load". I think `get_authorizers_by_scope()` and `load_tokens_by_scope()` are doing conceptually the same thing (returning authorizers/token after successful login), but using "get" on one and "load" on the other is confusing. Or, maybe they are doing very different things and I'm just still confused.

If the intent of `load_tokens_by_scope()` is indeed to return a map of scopes -> access token strings, then I definitely see the value in that, I would just go with a naming approach more like `get_tokens_by_scope()` to match `get_authorizers_by_scope()`.

**Comment by NickolausDS** [comment]
I suggested `get_authorizers_by_scope()` and `load_tokens_by_scope()`  to follow the current methods `get_authorizers()` and `load_tokens()`. `load_tokens()` should probably stay the same since it corresponds to `save_tokens()` and implies saving and loading to/from disk. However, I see how the difference in verbs is confusing. Maybe it would make more sense to have `load_authorizers()` instead? 

Getting tokens and getting authorizers do different things. 

`load_tokens()`: 

* Check if token management is set (custom or default).
* Load tokens from disk
* If a list of requested scopes were provided, check that they match. #22 relaxes this to 'subset'.
* Check if tokens are expired
    * If a refresh token was provided, do a 'refresh' and save the new tokens.

`get_authorizers()`:

* Calls load tokens
* loads the refresh token authorizers if possible, otherwise access token authorizer
* if refresh tokens, sets the refresh hook to save the newly refreshed tokens to disk.

**Comment by jimPruyne** [comment]
Per our discussion Friday:

- Auth generates single Access/Refresh token values for a set of scopes in a single grant request.

- We also request a login based on a set of scopes (`requested_scopes=`)

Thus, the unit of getting back authorizers or tokens should also be the set of scopes.

We should consider two distinct scope sets, even if they overlap (ie I have non null intersection), to be entirely different entities with respect to the autorizer they can generate, the tokens (access and refresh) they can return.

It therefore follows that token storage should be keyed on the set of scopes.

**Comment by NickolausDS** [comment]
If I'm following the requirements correctly, you're still asking for the same two methods above to get tokens by scope. The discussion Friday changes the behavior of multiple login flows -- new logins will save new token sets independently from old token sets. The token set returned by NativeClient will depend on the `requested_scopes` passed in. 

* `cli.load_tokens_by_scope(requested_scopes=['profile'])`
* `cli.get_authorizers_by_scope(requested_scopes=['profile', 'openid'])`

Without going into detail of how NativeClient will choose which Token Set for a given requested scope, does this track with you so far?

**Comment by jimPruyne** [comment]
Did we settle the design on this? If you feel like you're blocking on me at all, let me know. I think your last comment summarized it properly.

**Comment by NickolausDS** [comment]
Nope, just confirmation I was tracking everything correctly. Is there any immediate need for these changes?

**Comment by jimPruyne** [comment]
No immediate need. I'll adopt this for the Automate Client whenever it is ready, so when I know its in place I'll schedule that bit of work on Automate.

**Comment by NickolausDS** [comment]
I'm starting on this now, (plus #27). Sorry for all the delay.

**Comment by NickolausDS** [comment]
#41 should address these issues, you can now load tokens and authorizers by scope using the methods above. Please reopen if something is missing.
