### ISSUE TITLE
Code Architecture change for saving/loading tokens

### ISSUE THREAD

**Issue by NickolausDS** [fair-research/native-login#4]
If you define your own config, the code architecture requires you to subclass an intermediate object for the `NativeClient` object to save tokens to your custom config. An implementation looks like this:

    class MyConfig(ConfigParser):
        def save(self, tokens):
            cfg = ConfigParser()
            for name, value in flat_pack(tokens).items():
                cfg.set('tokens', name, value)
            with open('mystore.cfg', 'w') as configfile:
                cfg.write(configfile) 
        
        # load() and clear() also go here
    
    config = MyConfig()
                
    class MyTokenStorage(TokenStorage):
        def save_tokens(self, tokens):
            config.save(tokens)
            
        # load() and clear() also go here
            
    client = NativeClient(token_storage=MyTokenStorage())
    # Saves tokens to 'mystore.cfg'
    client.login()

The style above for subclassing requires a bit of duplicating effort and learning about `TokenStorage` classes. We could take advantage of python's duct typing and instead just require that a config file have three methods: `save_tokens()`, `load_tokens()`, `clear_tokens()`. The result would look like this:

    class MyConfig(ConfigParser):
        def save_tokens(self, tokens):
            cfg = ConfigParser()
            for name, value in flat_pack(tokens).items():
                cfg.set('tokens', name, value)
            with open('mystore.cfg', 'w') as configfile:
                cfg.write(configfile) 
        
        # load() and clear() also go here
    myconfig = MyConfig()
            
    client = NativeClient(config=myconfig)
    # Saves tokens to 'mystore.cfg'
    client.login()

A third option would be multiple inheritance:

    class MyConfig(ConfigParser, TokenStorage):
        def save_tokens(self, tokens):
            <implementation>

    myconfig = MyConfig()
            
    client = NativeClient(config=myconfig)
    # Saves tokens to 'mystore.cfg'
    client.login()

**Comment by rpwagner** [comment]
The middle option (3 public methods, single inheritance) seems like the practical choice.

**Comment by NickolausDS** [comment]
Done
