### ISSUE TITLE
Registration and configuration documentation

### ISSUE THREAD

**Issue by lliming** [fair-research/native-login#7]
The README says only "First you must register a client." On the same line (as if it were part of the same idea), it gives the usage for the code in an app. 

1. These shouldn't be on the same line. They're different ideas, so they need separate paragraphs.
2. Instructions for client registration are missing. At a minimum, this should point to the Globus doc (https://docs.globus.org/api/auth/developer-guide/#register-app), tell the user to check the Native App checkbox, tell the user to include http://localhost as a redirect URI (if that's still necessary), and tell the user to get the client ID from the registration.

FWIW, I could help with this if you don't have time.

**Comment by NickolausDS** [comment]
This is really helpful, thanks! Yes, could you open a PR?

**Comment by lliming** [comment]
Turns out we no longer need to register http://localhost to use it as a redirect URI.

**Comment by lliming** [comment]
Merge PR#9 to resolve this.

**Comment by NickolausDS** [comment]
Thanks, let me know if you find anything else!
